Unite the Mealy machine and the Moore machine to the Mealy-Moore machine
spbu-se/KotlinAutomataConstructor pull request #6
Opened 2022-07-13 20:17 UTC by AzimMuradov

2022-07-13 21:20 UTC, IlyaMuravjov requested changes

2022-07-13 21:20 UTC, IlyaMuravjov commented on src/main/kotlin/automaton/constructor/model/property/DynamicPropertyDescriptors.kt
> +        displayValueFactory: ((Char?) -> String)? = null
Короче будет добавить функцию-расширение `DynamicPropertyDescriptor<T>.withDisplayValueFactory(displayValueFactory: (T) -> String): DynamicPropertyDescriptor<T>`, а не во все фабричные методы этот параметр добавлять.

2022-07-13 21:20 UTC, IlyaMuravjov commented on src/main/kotlin/automaton/constructor/view/AutomatonElementView.kt
> +        stringBinding(automatonElement, *automatonElement.allProperties.toTypedArray()) {
Для переходов `allProperties` -- это сразу все свойства самого перехода и состояния, в которое производится переход, поэтому тут надо вернуть, как было, или сделать, чтобы `allProperties` включало только свойства самого перехода, и поправить все использования `allProperties`.

2022-07-14 10:57 UTC, AzimMuradov commented on src/main/kotlin/automaton/constructor/view/AutomatonElementView.kt
> +        stringBinding(automatonElement, *automatonElement.allProperties.toTypedArray()) {
Сделаю первое, но в будущем надо поправить, потому что название может сбить с толку.

2022-07-14 10:58 UTC, AzimMuradov commented on src/main/kotlin/automaton/constructor/model/property/DynamicPropertyDescriptors.kt
> +        displayValueFactory: ((Char?) -> String)? = null
Хорошо, тогда я еще добавлю метод `copy` для `DynamicPropertyDescriptor` для того, чтобы реализовать `withDisplayValueFactory` (делать его `data class`-ом считаю не очень корректным потому что это совсем другая семантика).

2022-07-14 10:58 UTC, AzimMuradov commented on src/main/kotlin/automaton/constructor/model/property/DynamicProperty.kt
> +    val displayValue: String get() = descriptor.displayValueFactory(value)
К сожалению, если переименовать его в `toShortString()`, то мы изменим его семантику, предполагается, что `displayValue` это то значение, которое видно пользователю "на картинке", а в `toString()` возвращается сериализованное представление динамического свойства (иначе говоря его текстовый **эквивалент**). Поэтому `toShortString()` не совсем отражает действительность, т.к. мы фактически берем значение для просмотра, а не краткое значение динамического свойства.

2022-07-14 10:59 UTC, AzimMuradov commented on src/main/kotlin/automaton/constructor/model/automaton/MealyMooreMachine.kt
> +        const val NAME = "Mealy-Moore machine"
Хорошо)

2022-07-14 14:24 UTC, IlyaMuravjov commented on src/main/kotlin/automaton/constructor/model/property/DynamicPropertyDescriptors.kt
> +        displayValueFactory: ((Char?) -> String)? = null
Отличная идея, мы же разрабатываем на Kotlin с именованными и опциональными параметрами, а не на Java!

2022-07-14 14:25 UTC, IlyaMuravjov commented on src/main/kotlin/automaton/constructor/view/AutomatonElementView.kt
> +        stringBinding(automatonElement, *automatonElement.allProperties.toTypedArray()) {
Согласен, причём поправить, думаю, лучше изменением не семантики, а имени свойства `allProperties` так, чтобы оно отражало включение неявных свойств, полученных из целевого состояния. В противном случае название может сбить с толку, когда нужны все свойства, включая неявные.

2022-07-14 14:31 UTC, IlyaMuravjov commented on src/main/kotlin/automaton/constructor/model/memory/output/AbstractOutput.kt
> +        ).withDisplayValueFactory { if (it == EPSILON_VALUE) "" else it.toString() }
То, что это в `companion object` -- скрытый баг, который проявится, если всё таки сделать автомат с несколькими выводами.

2022-07-14 15:43 UTC, AzimMuradov commented
Поправил

2022-07-14 15:48 UTC, AzimMuradov commented
Исправил ошибочку :face_exhaling:

2022-07-14 16:26 UTC, IlyaMuravjov approved these changes

2022-07-14 16:26 UTC, merged