add localization
spbu-se/KotlinAutomataConstructor pull request #7
Opened 2022-07-15 11:27 UTC by YuriUfimtsev

2022-07-16 18:36 UTC, IlyaMuravjov requested changes
Не локализована строка `"Automaton constructor file"` в `JsonAutomatonSerializer.kt`.

На всякий случай здесь напоминаю, что в Intellij Idea для быстрого переименования есть сочетание клавиш `Shift + F6`.

2022-07-16 18:36 UTC, IlyaMuravjov commented on src/main/kotlin/automaton/constructor/view/AutomatonView.kt
> +                            labels.getString("AutomatonView.Pane.Problems"),
Добавление `.Pane` не несёт полезной смысловой нагрузки.

2022-07-16 18:36 UTC, IlyaMuravjov commented on src/main/kotlin/automaton/constructor/view/AutomatonView.kt
> +                            ":\n"
Передавать `:\n`, как переменную, крайне странно. Предлагаю всегда приписывать `:\n` в конце сообщения.

2022-07-16 18:36 UTC, IlyaMuravjov commented on src/main/kotlin/automaton/constructor/view/StateView.kt
> +                Setting(labels.getString("StateView.InitialState"),
Предлагаю заменить ключ на `StateView.Initial` (аналогично `StateView.Final`).

2022-07-16 18:36 UTC, IlyaMuravjov commented on src/main/kotlin/automaton/constructor/view/memory/MemoryView.kt
> +        labels.getString("MemoryView.InputDataView").toProperty(),
Предлагаю заменить ключ на `MemoryView.InputData`.

2022-07-16 18:36 UTC, IlyaMuravjov commented on src/main/kotlin/automaton/constructor/view/module/executor/ExecutionLeafView.kt
> +                "$it ${executionState.status}"
Зачем здесь убраны скобки?

2022-07-16 18:36 UTC, IlyaMuravjov commented on src/main/kotlin/automaton/constructor/model/memory/tape/InputTape.kt
> +private val NAME: String = labels.getString("InputTape.NAME")
Локализовывать надо только использование для `displayName`. Эта константа ещё в качестве ключа типа при сериализации используется. Аналогично для других `MemoryUnitDescriptor`-ов.

2022-07-16 18:36 UTC, IlyaMuravjov commented on src/main/kotlin/automaton/constructor/model/module/ProblemDetector.kt
> +            labels.getString("ProblemDetector.REMOVE_TRANSITIONS_FROM_FINAL_STATES_MESSAGE")
Слово `MESSAGE` неинформативно в контексте ключей локализации. Ещё не единообразно: все другие имена ключей были в CamelCase, а тут почему-то по-другому.

2022-07-16 18:43 UTC, IlyaMuravjov commented on src/main/kotlin/automaton/constructor/utils/I18N.kt
> +    }
Имя `labels`, на мой взгляд, неудачное, особенно если использовать static import-ы.
Ещё стоит перенести всё из `messages_en.properties` в `messages.properties`, а `messages_en.properties` оставить пустым (подробнее [здесь](https://stackoverflow.com/a/36012203)).
```suggestion
   val messages: ResourceBundle = ResourceBundle.getBundle("messages", Locale.getDefault())
```

2022-07-17 14:16 UTC, IlyaMuravjov requested changes

2022-07-17 14:16 UTC, IlyaMuravjov commented on src/main/kotlin/automaton/constructor/model/memory/Stack.kt
> +@SerialName("Stack")
Стоит продолжить использовать константу `NAME`. Аналогично в других `MemoryUnitDescriptor`-ах.

2022-07-17 14:16 UTC, IlyaMuravjov commented on src/main/resources/messages.properties
> +AutomatonDescriptionProvider.EpsilonTransitions=epsilon transitions
Должны быть два сообщения `with epsilon transitions` и `without epsilon transitions`, чтобы не было проблем с несогласованным переводом на русский, например, после перевода не должно получаться `с эпсислон-переходов` или `без эпсилон-переходами`.

2022-07-18 09:57 UTC, YuriUfimtsev commented
Хороший вопрос. Там еще возникла проблема с локализацией имен автоматов, поэтому это пока не окончательная версия

2022-07-18 10:34 UTC, IlyaMuravjov approved these changes

2022-07-18 10:35 UTC, merged